## Лабораторная работа 4.1.2

In [114]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.optimize as sp
import tikzplotlib as tikz

In [115]:
def csvtotex(input, output, columns=None, rows=[-1], type=None, transp=False):
    df = pd.read_csv(input, sep=",", usecols=columns, quotechar='"', dtype=type)
    df = df[df.index.isin(rows)]
    if transp:
        df = df.transpose()
        pd.DataFrame.to_csv(df, output, sep="&", index=True)
        with open(output, "r") as data:
            content = data.readlines()
        with open(output, "w") as data:
            data.write("\\begin{tabular}{")
            for c in rows: data.write("|l")
            data.write("|l|}")
            data.write("\hline")
            content.pop(0)
            for str in content:
                data.write(str)
                data.write("\\\\")
                data.write("\hline")
            data.write("\end{tabular}")
    else:
        pd.DataFrame.to_csv(df, output, sep="&", index=False)
        with open(output, "r") as data:
            content = data.readlines()
        with open(output, "w") as data:
            data.write("\\begin{tabular}{")
            for c in columns: data.write("|l")
            data.write("|}")
            data.write("\hline")
            for str in content:
                data.write(str)
                data.write("\\\\")
                data.write("\hline")
            data.write("\end{tabular}")
    return df

In [116]:
def print_err(a, a_err, vis=True):
    a = np.array([a]).flatten()
    a_err = np.array([a_err]).flatten()
    val = np.zeros_like(a)
    sig = np.zeros_like(a_err)
    for i in range(a.size):
        val[i] = np.round(a[i], decimals = round(1 * (np.trunc(np.log10(a_err[i]) < 0)) - np.trunc(np.log10(a_err[i]))))
        sig[i] = np.round(a_err[i], decimals = round(1 * (np.trunc(np.log10(a_err[i]) < 0)) - np.trunc(np.log10(a_err[i]))))
        if vis: print(val[i], '\pm', sig[i])
    return val, sig

In [117]:
def T(n, x):
    return np.cos(n * np.arccos(x))

In [118]:
df = pd.read_csv('../data/data.csv')

>### Определение фокусных расстояний тонких линз с помощью зрительной трубы

In [119]:
csvtotex('../data/data.csv', '../data/table1.tex', range(0, 4), range(0, 2), type=int)
f_1, f_2, f_3, f_4 = df[df.columns[0:4]].head(1).values.reshape(-1,)

Рассеивающа линза

In [120]:
a, l = df[df.columns[5:7]].head(1).values.reshape(-1,)
err = 1

In [121]:
f_5 = a - l
f_5_err = (err ** 2 + err ** 2) ** 0.5
print_err(f_5, f_5_err)

70.0 \pm 1.0


(array([70.]), array([1.]))

>### Труба Кеплера

Через фокусы

In [122]:
f_err = 1
g = f_4 / f_2
g_err = g * ((f_err / f_4) ** 2 + (f_err / f_2) ** 2) ** 0.5
print_err(g, g_err)

2.6 \pm 0.03


(array([2.6]), array([0.03]))

Через угловой размер

In [123]:
l1, l2 = df[df.columns[8:10]].head(1).values.reshape(-1,)
l_err = 0.1

In [124]:
g = l2 / l1
g_err = g * ((l_err / l1) ** 2 + (l_err / l2) ** 2) ** 0.5
print_err(g, g_err)

2.7 \pm 0.3


(array([2.7]), array([0.3]))

Через диаметры

In [125]:
d1, d2 = df[df.columns[10:12]].head(1).values.reshape(-1,)
d_err = 1

In [126]:
g = d1 / d2
g_err = g * ((d_err / d1) ** 2 + (d_err / d2) ** 2) ** 0.5
print_err(g, g_err)

2.6 \pm 0.2


(array([2.6]), array([0.2]))

>### Труба Галилея

Через фокусы

In [127]:
f_err = 1
g = f_4 / f_5
g_err = g * ((f_err / f_4) ** 2 + (f_5_err / f_5) ** 2) ** 0.5
print_err(g, g_err)

4.04 \pm 0.08


(array([4.04]), array([0.08]))

Через угловой размер

In [128]:
l1, l2 = df[df.columns[13:15]].head(1).values.reshape(-1,)
l_err = 0.1

In [129]:
g = l2 / l1
g_err = g * ((l_err / l1) ** 2 + (l_err / l2) ** 2) ** 0.5
print_err(g, g_err)

3.9 \pm 0.4


(array([3.9]), array([0.4]))

>### Микроскоп

In [130]:
g = 5
L = 250
delta = 5 * f_1 * f_2 / L + f_1 + f_2
delta

360.22

In [131]:
l1, l2 = df[df.columns[16:18]].head(1).values.reshape(-1,)
l_err = 0.1

In [132]:
g = (l2 / l1) * (L / f_3)
g_err = g * ((l_err / l1) ** 2 + (l_err / l2) ** 2 + (f_err / f_3) ** 2) ** 0.5
print_err(g, g_err)

5.3 \pm 0.6


(array([5.3]), array([0.6]))